<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Top menu for store
 *
 * @see \Magento\Theme\Block\Html\Topmenu
 */
?>

<?php $columnsLimit = $block->getColumnsLimit() ?: 0; ?>
<?php $_menu = $block->getHtml('level-top', 'submenu', $columnsLimit) ?>
<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$customerSession = $objectManager->get('Magento\Customer\Model\Session');
$request = $objectManager->get('Magento\Framework\App\Action\Context')->getRequest();
$urlInterface = $objectManager->get('Magento\Framework\UrlInterface');

?>
<!-- <div class="navigation"> -->
    <ul data-mage-init='{"menu":{"responsive":true, "expanded":true, "position":{"my":"left top","at":"left bottom"}}}'>
      
       <li class="level0<?php if ($request->getFullActionName() == 'cms_index_index' || $urlInterface->getCurrentUrl() =='frames') { ?> active<?php }?>">
        <a href="<?php echo $this->getBaseUrl() ?>frames">Frames</a>
       </li>
       <li class="level0<?php if ($urlInterface->getCurrentUrl() ==  $this->getBaseUrl().'samples') { ?> active<?php }?>"> 
        <a href="<?php  echo $this->getBaseUrl()?>samples"> Samples</a>
        </li>
        <?php /* @escapeNotVerified */ //echo $_menu; ?>
        
        <li class="level0<?php if ($urlInterface->getCurrentUrl() ==  $this->getBaseUrl().'about') { ?> active<?php }?>"> 
        <a href="<?php  echo $this->getBaseUrl()?>about"> About</a>
        </li>
       
        <li class="level0<?php if ($urlInterface->getCurrentUrl() ==  $this->getBaseUrl().'contact-us') { ?> active<?php }?>"> 
        <a href="<?php  echo $this->getBaseUrl()?>contact-us"> Contact Us </a>
        </li>
        <li class="level0 <?php if ($request->getFullActionName() == 'customer_account_login') { ?> active <?php }?>" >
       <?php if($customerSession->isLoggedIn()){ ?>
            <a href="<?php echo $this->getUrl("customer/account/login") ?>">My Account</a>

      <?php }else{ ?>
            <a href="<?php echo $this->getUrl("customer/account/login") ?>">Login</a>
      <?php }?>
        </li>
        <?php if($customerSession->isLoggedIn()){ ?>
          <li class="level0"><a href="<?php echo $this->getUrl("customer/account/logout") ?>">Logout</a></li>
        <?php }?>
       <li class="level0 cartmenu">
        	<?php  echo $this->getLayout()
          ->createBlock('Magento\Checkout\Block\Cart\Sidebar')
          ->setTemplate('Magento_Checkout::cart/minicart.phtml')
          ->toHtml(); ?>


        </li> 
        <li class="level0<?php if ($urlInterface->getCurrentUrl() == 'frames') { ?> active<?php }?>">
          <a href="<?php echo $this->getBaseUrl() ?>frames">Select Frame</a>
        </li>
        
    </ul>

  <!-- </div> -->
   